# CDviz Monorepo Configuration
min_version = "2025.10.6" # "2025.9.7"
experimental_monorepo_root = true

[monorepo]
config_roots = [
    "cdviz-db",
    "cdviz-grafana",
    "cdviz-grafana/dashboards_generator",
    "cdviz-site",
    "demos",
    "demos/*",          # Single-level glob pattern
]

[settings]
experimental = true

[env]
# Shared registry for Helm charts
CHARTS_OCI_REGISTRY = "oci://ghcr.io/cdviz-dev/charts"

[tools]
yq = "latest" # used by build to update / normalize dashboards / release
git-cliff = "latest"
