apiVersion: v2
name: cdviz-grafana
description: Helm chart for cdviz-grafana - Grafana dashboards and datasources for CDviz SDLC observability platform
type: application
version: 1.2.0 # version set during release
icon: https://cdviz.dev/assets/favicon.svg
keywords:
  - sdlc
  - cd
home: https://cdviz.dev/
sources:
  - https://github.com/cdviz-dev/cdviz
appVersion: 1.2.0
